# Vector Agent 配置 - 簡化版本（更穩定）
# 自動收集本機日誌並回傳到中央 Vector 伺服器

# ==================== 數據源 ====================

# 收集系統日誌 (journald) - 排除 Vector 自己的日誌
[sources.system_logs]
  type = "journald"
  current_boot_only = false
  # 排除 vector 程序的日誌，避免收集自己的運行日誌造成迴圈
  exclude_matches._COMM = ["vector"]

# 收集 /var/log 下的所有 log 文件（排除 Vector 自己的日誌避免迴圈）
[sources.var_log_all]
  type = "file"
  include = ["/var/log/**/*.log"]
  exclude = ["/var/log/vector/**", "/var/log/vector-agent/**"]
  read_from = "end"
  ignore_older_secs = 86400

# 收集常見的系統日誌文件（無副檔名）
[sources.var_log_system]
  type = "file"
  include = [
    "/var/log/syslog",
    "/var/log/messages",
    "/var/log/auth.log",
    "/var/log/secure",
    "/var/log/kern.log",
    "/var/log/daemon.log"
  ]
  exclude = ["/var/log/vector/**", "/var/log/vector-agent/**"]
  read_from = "end"
  ignore_older_secs = 86400

# ==================== 數據轉換 ====================

# 過濾掉 Vector 自己的日誌（從 syslog 中）
[transforms.filter_vector_logs]
  type = "filter"
  inputs = ["var_log_system"]
  condition = '!includes(string!(.message), "vector[") && !includes(string!(.message), "vector:")'

# 添加主機資訊
[transforms.add_host_info]
  type = "remap"
  inputs = ["system_logs", "var_log_all", "filter_vector_logs"]
  source = '''
    .agent_hostname = get_hostname!()
    .collected_at = now()
    .source_agent = "vector-agent"
  '''

# ==================== 輸出到中央伺服器 ====================

# HTTP 方式回傳
[sinks.send_to_central]
  type = "http"
  inputs = ["add_host_info"]
  uri = "http://VECTOR_SERVER_IP:8080"
  encoding.codec = "json"

  # 批次發送設定
  batch.max_bytes = 1048576
  batch.timeout_secs = 5

  # 重試設定
  request.retry_attempts = 5
  request.retry_initial_backoff_secs = 1

# 本地備份（存放到已排除的目錄）
[sinks.local_backup]
  type = "file"
  inputs = ["add_host_info"]
  path = "/var/log/vector-agent/backup-%Y-%m-%d.log"
  encoding.codec = "json"

  # 注意：/var/log/vector-agent/** 已在上方 sources 中被排除
