name: Deploy Vector to Remote Host

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 允許手動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          cd /opt/vector-log-collection || mkdir -p /opt/vector-log-collection
          cd /opt/vector-log-collection

          # 下載最新配置
          curl -fsSL https://raw.githubusercontent.com/lucklyms/vector-log-collection/master/vector-final.toml -o vector-final.toml
          curl -fsSL https://raw.githubusercontent.com/lucklyms/vector-log-collection/master/deploy.sh -o deploy.sh
          chmod +x deploy.sh

          # 執行部署
          ./deploy.sh
